
# ??? ??
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${MariaDB_ID}
    password: ${MariaDB_PW}

# ?? ?? ?? ??? ??
  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'true'

# ???? ?? OFF
  thymeleaf:
    cache: 'false'
# jpa ??
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # ??? SQL ??? ???? ??? ??
    properties:
      hibernate:
        format_sql: true # SQL ??? ?? ?? ???
        dialect: org.hibernate.dialect.MySQL8Dialect
